server:
  port: 8010
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #  datasource:
  #    url: jdbc:mariadb://127.0.0.1:3306/rest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
  #    username: root
  #    password:
  datasource:
    url: jdbc:h2:mem:db_dev:MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: always